### ISSUE TITLE
WebGL Exception when pressing ctrl-Z

### ISSUE THREAD

**Issue by strategisgroep** [kou-yeung/WebGLInput#1]
This happens in my own proejct and the example at http://kou-http://kou-yeung.mygamesonline.org/WebGLInputSample/index.html

Google Chrome Version 74.0.3729.131.

How to reproduce:
1. Copy a text (browser url)
2. type "asd" in the ContentType:Standard field of the example.
3. select all by clicking the "asd" text.
4. paste browser url with ctrl+v
5. press ctr+z (undo) two times
6. exception
7. interestingly, application keeps working after exception

**Comment by kou-yeung** [comment]
thank you for report.
i will check it!

**Comment by kou-yeung** [comment]
fixed and release a new package.
