### ISSUE TITLE
unity 22.1.21 input text doesn't write in

### ISSUE THREAD

**Issue by anvarisoraya** [kou-yeung/WebGLInput#102]
I use unity 2022.1.21, have a form in unity 2D with 2 input texts. When I type in the first input, it starts writing in the second one and when I open the second text input file, I cannot write anything in that.

**Comment by gebalassa** [comment]
Weird. See that the "**Web GL Input** script is properly placed as a component on each Input Field.

**Comment by kou-yeung** [comment]
If it is still reproducing send me a reproduced project~
thanks!
