### ISSUE TITLE
Full screen issue when zooming browser

### ISSUE THREAD

**Issue by seungsunkim** [kou-yeung/WebGLInput#105]
Using document.makefullscreen, the phenomenon that text is input backwards during unity full screen has been fixed.

However, if document.makefullscreen is used, full screen results in black margins when the browser is zoomed in or zoomed out.
Any solution to this?

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.
