### ISSUE TITLE
An error occured running javascript

### ISSUE THREAD

**Issue by knorro** [kou-yeung/WebGLInput#106]
<img width="439" alt="Scherm­afbeelding 2023-01-25 om 19 26 08" src="https://user-images.githubusercontent.com/121129646/214650819-742b94e1-f8b5-41cb-817b-4d6ee94e4c27.png">

**Comment by NormanCorma** [comment]
I meet this problem on the latest vershin too, but it solve when I uset the [1.2 ver](https://github.com/kou-yeung/WebGLInput/releases/tag/1.2)

**Comment by kou-yeung** [comment]
if reproduction at new release. reopen it.
thanks~
