### ISSUE TITLE
Copy Button

### ISSUE THREAD

**Issue by mhadji05** [kou-yeung/WebGLInput#107]
I want to add a Button next to a text and when I press the Button must copy the text-string.

The tries below are not working.

1) GUIUtility.systemCopyBuffer = s;

2) UnityEngine.TextEditor s2 = new UnityEngine.TextEditor();
    s2.text = "Hello world";
    s2.SelectAll();
    s2.Copy();

Please let me know how can i replace the systemCopyBuffer command in WebGL.

Thanks in advance.

**Comment by kou-yeung** [comment]
maybe you can try clipboard web api .
FYR: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

this plugins is use input element to input text.
so, this can copy and paste with default behavior...

**Comment by mhadji05** [comment]
Can you provide Unity C# code please o example project.

Thanks in advance.
