### ISSUE TITLE
container is null

### ISSUE THREAD

**Issue by mhadji05** [kou-yeung/WebGLInput#108]
Here is the error:

An error occurred running the Unity content on this page. See your browser JavaScript console for more info. The error was:
TypeError: container is null
_WebGLInputCreate@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312:3:68288
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[30849]:0x9b037d
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[15539]:0x4aaca5
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[65332]:0x11a23b1
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[45210]:0xdd4dbb
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[8926]:0x2ae055
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[34262]:0xa60947
invoke_iiii@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312:3:401414
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[1645]:0x85b95
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[16779]:0x509594
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[833]:0x5b4e8
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[12241]:0x3e4783
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[43218]:0xd5b973
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[17718]:0x59f3b6
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[37261]:0xae9d35
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[19747]:0x71ffbb
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[19747]:0x72002c
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[16957]:0x51fad0
@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312 line 3 > WebAssembly.instantiate:wasm-function[34257]:0xa60909
browserIterationFunc@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312:3:229531
callUserCallback@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312:3:182729
runIter@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312:3:184005
Browser_mainLoop_runner@blob:http://localhost:53740/dafff522-8afd-467f-a927-f4f5f5d4b312:3:182264

I tried to change WebGLInput.CanvasId = "unity-canvas";

A new error presented. When i m righting on the inputfield letters written reverse

e.g: hello --> olleh

any solution?

**Comment by kou-yeung** [comment]
which Unity version you used..?

**Comment by mhadji05** [comment]
Unity 2021.3.8

**Comment by mhadji05** [comment]
Any idea how to solve it?

**Comment by mhadji05** [comment]
@kou-yeung  any idea how to fix this problem?

**Comment by kou-yeung** [comment]
i tried to build master branch with Unity2021.3.8.
it is worked.

**Comment by CitaTo** [comment]
My solution is revert this commit and everything work well. Not sure what is multiple canvas, may be i do not need it.
https://github.com/kou-yeung/WebGLInput/commit/72f5db88248404e522364200660369410ab576d6

**Comment by Varia7** [comment]
I came with this problem too. It happens probably because different unity versions use different html id on canvas. Check if WebGLInput.CanvasId in the file WebGLInput.cs and the id of the canvas in the html of your build are matched.

**Comment by mhadji05** [comment]
any solution?

WebGLInput.cs id => WebGLInput.CanvasId = "unity-container";

index.html line => var canvas = document.querySelector("#unity-canvas");

If i change this with the same text the result is not working.

Please let me know if there is a solution on this issue?

Thanks
