### ISSUE TITLE
The caret position and text position is not updated when using Text Mesh Pro

### ISSUE THREAD

**Issue by QuocHieuNguyen** [kou-yeung/WebGLInput#110]
Environment: Unity 2021.3.19

Steps to reproduce:
- Create an Input Field with Text Mesh Pro.
- Add the WebGL Input Component
- Build in WebGL platform
- Type word in that input field until the total length of the text is out of bound to the input field
- Delete words by clicking "Backspace"
- The caret position and text position is not updated, they should move to the left until the text area is fit to the input field

Full video description is here: https://drive.google.com/file/d/14hU8UGToFLMsZ0CuRh-fSWf58ObmuU08/view?usp=sharing

If you want more information pls let me know.

**Comment by kou-yeung** [comment]
i tried at unity editor. this is unity default behavior...
but has some other issue when re-select the inputfield is has not show at left.

**Comment by QuocHieuNguyen** [comment]
You have any idea for solutions or any work around ? This issue only emerges when using TMP, normal Text Input Field is fine. But in my project, I have to support IME for Japanese Typing and your font, SoukouMincho, has lots of missing character (result in the square symbol). Any idea for more supported font format ?

**Comment by kou-yeung** [comment]
SoukouMincho is a free font. you can use other font asset you want..
and to set the "character set".
FYR : https://docs.unity3d.com/Packages/com.unity.textmeshpro@4.0/manual/FontAssetsCreator.html

**Comment by QuocHieuNguyen** [comment]
Yeah, there is no issue when using normal Text (which does not have FontCreator feature like TMP). But using Input Field with Text Mesh Pro results in the aforementioned issue. If there is a font that fully supports all Japanese Character, pls let me know. I will try this work around.

**Comment by kou-yeung** [comment]
The problem can be solved by preparing a font. close..
If there is anything else you would like to know, please comment
