### ISSUE TITLE
焦点问题

### ISSUE THREAD

**Issue by quwanli** [kou-yeung/WebGLInput#112]
您好，Android平台输入框输入完内容不点WebGL画布空白区域而是点击Unity内的交互按钮，系统软键盘关不掉。怎么解决？尝试代码调WebGLInput里的DeactivateInputField()能关掉，但再次点击输入框会有时弹不出系统键盘。

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2
