### ISSUE TITLE
iOS not support plugin 

### ISSUE THREAD

**Issue by hina9** [kou-yeung/WebGLInput#113]
In iOS version 16.5 the 
InputField is selected, a mobile input key is generated, but the input is not properly supported.

I checked Safari, Chrome and found that the same input is not supported.

Please let me know how to fix it.

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2

if reproduction at new release. reopen it.
thanks~
