### ISSUE TITLE
unity2021全屏后直接打不出字了,需要禁用脚本才能输入英文

### ISSUE THREAD

**Issue by cuijuncheng** [kou-yeung/WebGLInput#115]
document.makeFullscreen('unityContainer')的方法试过了 并没有什么用，请问有什么办法解决吗？ 感谢了

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.
