### ISSUE TITLE
Selection lost on alt tab

### ISSUE THREAD

**Issue by StefanStrategis** [kou-yeung/WebGLInput#12]
When selecting an input field and then alt tabbing out of the browser (chrome) causes the current inputfield selection to be lost. 

This is different from a browser's and unity's default behavior where it keeps its selection after an alt tab.

This can cause issues with for instance password managers that auto fill in fields or if the user wants to copy something into his current selection from another window.

It would be nice that the current selection would be kept on alt tabbing.

**Comment by kou-yeung** [comment]
when browser tab change.the input field will call onblur and then window.onblur will call.
i will try to use window.onblur and window.onfocus to handle this issues.

**Comment by kou-yeung** [comment]
i have release a new version to fix this issue.
thank you for report~

**Comment by kou-yeung** [comment]
fix a bug.when switch tab fast (eg. hold Ctrl + tab)
