### ISSUE TITLE
unity2021 can not type directly after the full screen, you need to disable the script to enter English

### ISSUE THREAD

**Issue by cuijuncheng** [kou-yeung/WebGLInput#120]
document.makeFullscreen('unityContainer') no use

**Comment by akroshteotia** [comment]
The correct line is document.makeFullscreen('unity-container'); but still it wont do anything

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.
