### ISSUE TITLE
How to remove the closeup input field?

### ISSUE THREAD

**Issue by Shalevvv1** [kou-yeung/WebGLInput#122]
Hi!
Is there a way to remove the closeup input field that appears when I focus on UI input field?

![WhatsApp Image 2023-08-16 at 12 11 23 PM](https://github.com/kou-yeung/WebGLInput/assets/111116204/50c57654-4091-46a3-b92a-fa6aaeee1a93)

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2

use this new release after [1.3.1](https://github.com/kou-yeung/WebGLInput/tree/1.3.1)
it will auto switch to use default mobile implementation
