### ISSUE TITLE
macOS webGL is needed

### ISSUE THREAD

**Issue by aiXia121** [kou-yeung/WebGLInput#123]
i'm navie at unity stater, would u mind supporting the mac os webGL is needed?

thanks

**Comment by kou-yeung** [comment]
i tried at macOS Sonoma 14.1.2 is worked.
safari 17.1.2
chrome 124.0.6367.158

**Comment by kou-yeung** [comment]
if has same issues.
reopened this issue and tell me your test version.
thanks~
