### ISSUE TITLE
Doesn't work on latest Unity LTS version 2022.3.10f1

### ISSUE THREAD

**Issue by DavidT76** [kou-yeung/WebGLInput#124]
I am a Windows 11 laptop with Unity version 2022.3.10f1. I don't see the WebGL component you talk about in the Readme text file. I tried adding your scripts to my Input text field object but it did not fix the issue I had the mobile keyboard appearing in my WebGL app on a mobile device. Here is a screenshot of where placed two of your scripts:
 
![Screenshot 2023-10-01 212608](https://github.com/kou-yeung/WebGLInput/assets/55117157/d8555153-26a5-4664-a05f-66972d8e5d4a)

That was the only way I could think of getting my game to use your scripts. I may not have done it correctly or there is a bug in your code.

**Comment by kou-yeung** [comment]
no need to add WebGLInputMobile. it will auto add from script in runtime when in mobile device.

and mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2

if reproduction at new release. reopen it.
thanks~
