### ISSUE TITLE
Copy does not include new lines

### ISSUE THREAD

**Issue by SilverDubloons** [kou-yeung/WebGLInput#125]
Hi and thanks for your time!

I'm building a Wordle-style daily game in Unity and publishing on itch.io using WebGL. I have a button that when clicked, copies a string to the users clipboard. This works fantastically in the Unity editor, but not in WebGL. Probably why we're all here.

When I copy my generated text from within the editor, it seems to work as expected, new lines and all. However, when I test my output game on itch.io using this plugin, it copies everything but the line breaks. I've tried replacing "/n" with Environment.NewLine but this hasn't changed a thing. Is there a way to get this functionality?

It might be related to another question I have - it seems that no special characters can be copied. I was originally trying to use characters like the ones generated in this Discord colored text generator:

https://rebane2001.com/discord-colored-text-generator/

but certain characters generated from that are just copied as hollow squares.

Anyone have any insight into how to solve this? Thanks again!

For reference, here's my 'ideal' block of text that I would like to be able to copy from an inputfield:

:diamonds:Daily GridPoker for 2023-10-10 Seed = ||465514976|| Total Score = ||82||:diamonds:
||```ansi
    --------------------  2
    |[2;30m[2;30m5♠[0m[2;30m[0m  [2;36m[2;36m8♣[0m[2;36m[0m  [2;36m[2;36mK♣[0m[2;36m[0m  [2;30m[2;30m3♠[0m[2;30m[0m  [2;31mA♥[0m|  2
    |[2;36m[2;36mA♣[0m[2;36m[0m  [2;30m[2;30mK♠[0m[2;30m[0m  [2;31m[2;34m9♦[0m[2;31m[0m  [2;36m[2;36m9♣[0m[2;36m[0m  [2;31m[2;34m2♦[0m[2;31m[0m|  12
    |[2;31m[2;34mA♦[0m[2;31m[0m  [2;31m[2;34mK♦[0m[2;31m[0m  [2;31m8♥[0m  [2;36m[2;36m2♣[0m[2;36m[0m  [2;31m[2;34mT♦[0m[2;31m[0m|  2
    |[2;31m[2;34m7♦[0m[2;31m[0m  [2;30m[2;30mT♠[0m[2;30m[0m  [2;30m[2;30m8♠[0m[2;30m[0m  [2;36m[2;36m4♣[0m[2;36m[0m  [2;31m[2;34mJ♦[0m[2;31m[0m|  1
    |[2;30m[2;30m6♠[0m[2;30m[0m  [2;31mJ♥[0m  [2;31m3♥[0m  [2;31m2♥[0m  [2;31m[2;34m8♦[0m[2;31m[0m|  1
    --------------------
     17  16  11  5   2  11
```||

But even if I could just get line breaks working, I would be happy with that with this sytle of output:

:diamonds:Daily GridPoker for 2023-10-10 Seed = ||465514976|| Total Score = ||82||:diamonds:
||```
    --------------------  2
    |5♠  8♣  K♣  3♠  A♥|  2
    |A♣  K♠  9♦  9♣  2♦|  12
    |A♦  K♦  8♥  2♣  T♦|  2
    |7♦  T♠  8♠  4♣  J♦|  1
    |6♠  J♥  3♥  2♥  8♦|  1
    --------------------
     17  16  11  5   2  11
```||

**Comment by kou-yeung** [comment]
i tried coyp text at "Rebane's Discord Colored Text Generator" use Copy text as Discord formatted
and paste to memo app.
is same has □. so This is not a problem with this plugin.
