### ISSUE TITLE
any suggestion to support input on webmobile?

### ISSUE THREAD

**Issue by gianty-hungvt** [kou-yeung/WebGLInput#126]
Hi, 
I'm using this plugin and very satisfied because it works very well on webgl PC. Now my game needs to be played on webmobile, especially on iOS but only Japanese keyboard works. I looked at your code but don't really know how to fix it.

Do you have any direction or suggestion for me to add this support? Thank you very much

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2
