### ISSUE TITLE
Can't delete the first charactor in Safari

### ISSUE THREAD

**Issue by kmmtaro** [kou-yeung/WebGLInput#130]
When I type a word in japanese like「あいうえお」 and then try to clear input field by using back space key,
the first charactor (in this case, it is「あ」) remains and can't delete it.

It occurred only in Safari on paticular MacBook Pro.
ーーーー
MacBook Pro (Apple M1 Pro)
macOS: Ventura 13.6
Safari: Ver16.6

Unity Editor Version: 2021.3.24f1
ーーーー

It can be reproduced in demo site.
https://unityroom.com/games/webglinput

when I connected external monitor and displayed browser on the monitor, it didn't occur.
so I guess it's related to screen resolution or something like that, but I'm not sure…

**Comment by kou-yeung** [comment]
i tried at MacBook Pro (Sonoma14.1.2) Safari (17.1.2)
cann't reproduced it..._:(´ཀ`」 ∠):

**Comment by kmmtaro** [comment]
it may be related to model…？

technical specifications
ーーーー
MacBook Pro (14-inch, 2021)
https://support.apple.com/kb/SP854
ーーーー

and I realized that this bug occur only when typing backspace key without confiming a Japanese IME autocomplete candidate (pressing the enter key).

**Comment by kmmtaro** [comment]
i updatated mac os version to 14.2.1, and this bug stopped reproducing.
it may be related to specific os version…
anyway, it's solved.  thanks for check my issue.
