### ISSUE TITLE
GetElementsByTagName null

### ISSUE THREAD

**Issue by Bertko** [kou-yeung/WebGLInput#131]
![error_webgl](https://github.com/kou-yeung/WebGLInput/assets/4909147/78b881e6-713e-4967-861b-476735cbc4f8)
On Unity 2021.3.

**Comment by AEgorovCCR** [comment]
Same. 2021.3.0f1

**Comment by AEgorovCCR** [comment]
Found the reason. this part:
`static WebGLInput()
{
    WebGLInput.CanvasId =`

Gets incorrect canvas html element id. I replaced it with string containing my actual id and it works

**Comment by AEgorovCCR** [comment]
But the Ctrl-C Ctrl-V do not work in WebGL

**Comment by kou-yeung** [comment]
fixed : [1.2.3](https://github.com/kou-yeung/WebGLInput/tree/1.2.3)

if reproduction at new release. reopen it.
thanks~
