### ISSUE TITLE
On focus, even if the input is disabled

### ISSUE THREAD

**Issue by Biebras** [kou-yeung/WebGLInput#133]
I pressed on the input field that opened a virtual keyboard. However, while still focused, I pressed a button that disabled the input field. Now when I press on anything the virtual keyboard opens. How can I prevent this?

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2

**Comment by kou-yeung** [comment]
if reproduction at new release. reopen it.
thanks~
