### ISSUE TITLE
Unity6 support

### ISSUE THREAD

**Issue by kou-yeung** [kou-yeung/WebGLInput#144]
- [x] pc
- [x] mobile

**Comment by kou-yeung** [comment]
・PC issues
unity 6 build can not copy & paste.
Unity\6000.0.0f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\lib\CopyPaste.js
↑ was copy text from _GetCopyBufferAsCStr()

**Comment by kou-yeung** [comment]
モバイルは現状通り公式に任せる形で大丈夫と思います

- [ ] ビルドしてテスト

**Comment by dinkelstefan** [comment]
Unity 6.0 Changelog:
- Web: [Web Platform] Added the ability to copy and paste to and from the Unity player.

Is this plugin still necessary?

**Comment by kou-yeung** [comment]
@dinkelstefan 
yes...
because this plugins not only for copy and paste.
WebGLInput plugins make the inputfield to type with IME ( like. Japanese ) >.<

unity just support type with IME on mobile device.
PC still need this plugins. ( i think

**Comment by kou-yeung** [comment]
checked at 6000.0.7f1!
