### ISSUE TITLE
DynCall Deprecated: Switch to MakeDynCall in 2023.3+ for WASM Table support

### ISSUE THREAD

**Issue by dinkelstefan** [kou-yeung/WebGLInput#149]
dynCall is now deprecated, upgrade to makedyncall to enable wasm table support.

https://docs.unity3d.com/Manual/web-interacting-browser-deprecated.html

![image](https://github.com/kou-yeung/WebGLInput/assets/4303049/4fa8bac8-3328-4edd-9dfa-e7f531a20949)

**Comment by kou-yeung** [comment]
release a new version to support wasm table
https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.7
thanks~
