### ISSUE TITLE
Unity 2021.3.37f1 Support

### ISSUE THREAD

**Issue by Makotoooo** [kou-yeung/WebGLInput#153]
The newest WebGLInput  version 1.3.7 has compile errors with Unity version 2021.3.37f1.
when i use version 1.2, it just works.

The errors are as following:
![图片](https://github.com/kou-yeung/WebGLInput/assets/33192133/055e606b-d18d-4d25-b579-7d5f78329891)

**Comment by kou-yeung** [comment]
release a new version fixed it.
https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.8
thanks~
