### ISSUE TITLE
Please change Support.cs encode from Shift-JIS to UTF-8 with BOM

### ISSUE THREAD

**Issue by SyaoranChang** [kou-yeung/WebGLInput#157]
Hi.
I found a file named Support.cs with garbled code when I commit.
Because the encoding of this file is Shift-JIS 
Can you please change it to UTF-8 with BOM?

![Snipaste_2024-05-27_17-09-43](https://github.com/kou-yeung/WebGLInput/assets/18550228/ccd9b5da-9099-454f-a382-de7e2a7900cb)

**Comment by kou-yeung** [comment]
fixed.will release at next version~
thanks
