### ISSUE TITLE
Problems with autocomplete function [Cannot read properties of undefined (reading 'length')]

### ISSUE THREAD

**Issue by rodrigogpontes** [kou-yeung/WebGLInput#161]
Hi.
Recently we updated the version of WebGLInput plugin used in our projects, from 1.3.1 to 1.4.0, to correct the backwards typing problem with fullscreen mode, but now we are noticing a new problem with some TMPro InputFields who have the 'Content Type' = 'Email Address'.

When are used the autocomplete function to write an email address to a login field, this error happens:

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at lengthBytesUTF8 (f4a96543-38bc-446a-9579-7fdc60046107:2:13555)
    at func (f4a96543-38bc-446a-9579-7fdc60046107:2:76224)
    at HTMLInputElement.<anonymous> (f4a96543-38bc-446a-9579-7fdc60046107:2:76701)

I'm sending a picture of the error to a better anaysis. The game was tested using the 125.0.2535.92 version of Microsoft Edge browser in a Windows 11 environment, and the game was developed using Unity 2021.3.36f1.

Thanks in advance, and thanks again for making this so useful project for all of us.

_Best regards,
Rodrigo_

![error](https://github.com/kou-yeung/WebGLInput/assets/104315266/9040c93e-672b-40cd-8b98-8091b7815e80)

**Comment by kou-yeung** [comment]
i tried to build a sample to the this issue.
i was use Microsoft Edge( 126.0.2592.56 ). but my sample not showed the autocomplete to me.
I want to know more details.

1. autocomplete function was worked at WebGLInput 1.3.1 ?
2. if no need the autocomplete . you can try below change to WebGLInput.jslib
```
WebGLInput.jslib Line.75~
// before
if(isPassword){
    input.type = 'password';
}

// after
if(isPassword){
    input.type = 'password';
} else {
    input.autocomplete = 'off'; // set the autocomplete off
}
```
WebGLInput  has not passed "Content Type" to html element.
so, I don't know why the html element show the autocomplete to you ><

**Comment by rodrigogpontes** [comment]
Hi. Thanks for the reply!

Answering the questions:

> 1. autocomplete function was worked at WebGLInput 1.3.1 ?

Yes, with the older version the autocomplete browser's function work flawlessly, but we changed to the plugin's new version because the old one had problems with the fullscreen mode (backward typing, for example).

> 2. if no need the autocomplete . you can try below change to WebGLInput.jslib

We did the changes but, unfortunately, the problem persists. Edge continue showing the "Saved personal info" box when the user click on the e-mail field (see the next image). I'm not sure if this box is presented to all users or only to users who sign-in the Edge account like me.

![pic01](https://github.com/kou-yeung/WebGLInput/assets/104315266/bf322dab-66ea-47b5-9e6f-cf1a7605d984)

Reading a bit more about this error in the console, I suspect this is related with the new function _WebGLInputOnKeyboardEvent. In the next picture I'm sharing the sequence of calls, indicated by the browser's console, who give us error when we click on a e-mail address from the Edge's "Saved personal info" box.

![pic02](https://github.com/kou-yeung/WebGLInput/assets/104315266/a0cf1706-ee3f-4813-825a-a52edf208439)

_Best regards,
Rodrigo_

**Comment by kou-yeung** [comment]
thanks~
i got how to fix this issue.

autocomplete was post event for keydown.
but the event type is not "KeyboardEvent". ( autocomplete is post "Event"

so. i can check this instance is KeyboardEvent or not
like:
```
if (e instanceof KeyboardEvent){ }
```

**Comment by kou-yeung** [comment]
release a new version to fix this issue~
https://github.com/kou-yeung/WebGLInput/releases/tag/1.4.1

**Comment by rodrigogpontes** [comment]
Tested and working flawlessly.
@kou-yeung thank you!
