### ISSUE TITLE
The virtual keyboard cannot pop up when clicking on the input box in full screen on the phone

### ISSUE THREAD

**Issue by complete516** [kou-yeung/WebGLInput#163]
On Android and Google Chrome。
unity 2022.3.20f1

**Comment by kou-yeung** [comment]
virtual keyboard is showed without WebGLInput Plugins?
・if yes. it not this Plugins issues.

because mobile was support by Unity
InputField : from Unity2022.1
TMP_InputField : from Unity2023.2

**Comment by complete516** [comment]
Thank you for your reply.
Without WebGLInput plugins, the virtual keyboard will not be displayed.

**Comment by complete516** [comment]
> Using unity's InputField and TMP_InputField also does not display a virtual keyboard.

Thank you for your reply.
Using unity's InputField and TMP_InputField also does not display a virtual keyboard.

**Comment by complete516** [comment]
> virtual keyboard is showed without WebGLInput Plugins?
> 
> because mobile was support by Unity InputField : from Unity2022.1 TMP_InputField : from Unity2023.2

Thank you for your reply.
Using unity's InputField and TMP_InputField also does not display a virtual keyboard.
