### ISSUE TITLE
Problem with pasting url from browser address bar

### ISSUE THREAD

**Issue by zizul** [kou-yeung/WebGLInput#19]
Hi, I just run into a problem with pasting on Firefox
Was really hoping to use your solution, it's the best I could find.
No need to use javascript or html overlay popups to paste text to Unity WebGL.

Steps to reproduce in Firefox 68.0 (64 bits):
1. Copy url from browser address bar
2. Paste url into input field
3. Change url in address bar
4. Copy it again
5. Try to paste url into input field
6. Inputfield hangs, not possible to paste anything

**Comment by kou-yeung** [comment]
reproduce this issue.
i will check it.
thanks to report.

**Comment by kou-yeung** [comment]
i hane release a new version to fix this issue.
https://github.com/kou-yeung/WebGLInput/releases

**Comment by zizul** [comment]
Wow, works like a charm now! Thank you very much!
