### ISSUE TITLE
Screen not fixed, it scrolls to the bottom of the screen

### ISSUE THREAD

**Issue by babazookz** [kou-yeung/WebGLInput#23]
Hi, whenever I click on some Input Field the entire screen scrolls to the bottom of the screen.

When full screen, everything is fine.

What could go wrong? Do you want me to record a video?

EDIT: 
Video - https://drive.google.com/file/d/1LonEcbX7vDDUwKbh0AFprWbaaPEn0WGp/view?usp=sharing

**Comment by kou-yeung** [comment]
thanks for report.
can i have more info for this.

- reproduce Unity version.
- the inputfield maybe placement outside of screen?
 input element is created same position at inputfield object.
 so, browser will scroll to focus the input element.

**Comment by babazookz** [comment]
Unity 2019 is the version.

I am not sure what are you asking me but all my input fields are created on the screen, nothing outside.

Did you see the video?
Do you want me to send you the test scene?

**Comment by babazookz** [comment]
One thing to add, when I remove WebGLInput class from InputField object, this does not happen.

**Comment by kou-yeung** [comment]
・Did you see the video?
yes.i saw the video

・Do you want me to send you the test scene?
Yes,Please.

**Comment by kou-yeung** [comment]
![ss20190718_001](https://user-images.githubusercontent.com/7277282/61433394-209a7180-a96e-11e9-8399-6f401142d93e.png)
i tried your sample html.
the html input element is create at bottom left.
so, i want to confirm where is the inputfiled gameobject.

**Comment by babazookz** [comment]
But why is that? I did not put my input there.

Please can you check the test scene:
https://drive.google.com/file/d/1e8NbcS9lgZF2_kHamx3Hqgk_WQPbeA6q/view?usp=sharing

**Comment by babazookz** [comment]
And even I am having problems with enabling FullScreen mode after implementing changes (try to do it and let me know what could it be).

**Comment by kou-yeung** [comment]
when Canvas renderMode is ScreenSpace - Camera. input element is not calculated correctly.
i have release a new version to fix this issue.
thanks.

**Comment by kou-yeung** [comment]
for the fullscreen issue.
in Unity2019. UnityLoader.js will add "canvas.style.width="100%",canvas.style.height="100%" to the canvas.
i will find other workaround for this.

**Comment by babazookz** [comment]
Thank you!
I appreciate it, let me know if I can help you somehow.

I will test the new release with the input location fix and let you know.

**Comment by kou-yeung** [comment]
i found a workaround for Uity2019 to change fullscreen.

same workflow of this thread
https://github.com/kou-yeung/WebGLInput/issues/2#issuecomment-491657725

and edit the "unityContainer" style 
<div id="unityContainer" style="width: 960px; height: 600px"></div>
↓
<div id="unityContainer" style="width: 100%; height: 100%"></div>

i will add a tutorial to setup fullscreen.(or release a edited version of Template)

**Comment by babazookz** [comment]
Ok, I am waiting.

**Comment by kou-yeung** [comment]
i add a step by step tutprial for support fullscreen.
you can try it.^^
https://github.com/kou-yeung/WebGLInput/wiki/Support-FullScreen

**Comment by babazookz** [comment]
It is working perfectly!
