### ISSUE TITLE
Long string crashes application layout in WebGL - Windows scale more than 100%

### ISSUE THREAD

**Issue by zizul** [kou-yeung/WebGLInput#26]
Hi!
I found a bug, while working in 4k and FHD resolution. Replicable in Chrome and Firefox on Windows 10. 
Steps to reproduce:
1. Set Windows 10 resolution to 4K or FHD
2. Set Windows scale to more than 100% 
  2a. Right click desktop, click Display Settings option
  2b. In section Scale and Layout change to 175%, or 300%
3. In application, insert a very long text into input field with WebGLInput component 
4. String overflows input field and application layout crashes (part of window get black - screenshot)
![scalingwindows10-100764460-large](https://user-images.githubusercontent.com/7687810/61940716-4a6b1e00-af96-11e9-83e7-092846d80264.jpg)
![2019-07-26 10_36_55-](https://user-images.githubusercontent.com/7687810/61940733-5656e000-af96-11e9-84ee-3b8bc37af702.png)

**Comment by kou-yeung** [comment]
thanks to report.
i will check it.

**Comment by zizul** [comment]
Any news about this one?

**Comment by zizul** [comment]
I know you're propably busy with other stuff, but is there any chance for a fix?

**Comment by kou-yeung** [comment]
Can I have more information.
this issue can reproduce at the sample page?
http://kou-yeung.mygamesonline.org/WebGLInputSample/index.html

if not.
can you send me a project to reproduce this isuue?

**Comment by zizul** [comment]
I cannot replicate it on you test page.
Will try to put together an example.

**Comment by kou-yeung** [comment]
i will close this issue.
thanks~
