### ISSUE TITLE
Hello, may I ask if the problem of not being able to enter the project after I try to compile it and run it in full screen has always existed?

### ISSUE THREAD

**Issue by soulzhuanshumm** [kou-yeung/WebGLInput#27]

**Comment by soulzhuanshumm** [comment]
But with my full screen input of your test project there is no problem is there any special Settings for the Unity editor

**Comment by kou-yeung** [comment]
this plugin will create input element and add it to div element ( same hierarchy of canvas )
the Unity Default Template will make canvas to fullscreen.
so. this plugins not work.

you can follow this wiki to support fullscreen.
https://github.com/kou-yeung/WebGLInput/wiki/Support-FullScreen

this can change the fullscreen target to upper element.

**Comment by soulzhuanshumm** [comment]
thanks
