### ISSUE TITLE
Safari Full Screen not working

### ISSUE THREAD

**Issue by babazookz** [kou-yeung/WebGLInput#28]
Hey, on Safari full screen invoke is not working but in Chrome and Firefox it is ok.

Here is the error for your reference:
https://i.imgur.com/iAPeoh9.png

**Comment by kou-yeung** [comment]
Safari not support  HTML5 Fullscreen API.
on safari must use webkitRequestFullscreen()
FYR: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

**Comment by kou-yeung** [comment]
i will edit wiki for this issue.

**Comment by babazookz** [comment]
And one more thing, Full Screen is not working in Firefox too. Can you please check that too?

**Comment by babazookz** [comment]
Any news on fixing Safari and Firefox full screen?

**Comment by kou-yeung** [comment]
i testing a new solution for fullscreen.

when call fullscreen function.
1. create a new div element and add it to body.
2. find canvas element and add it to the new div element.
3. make div element to fullscreen.

i will make it solution inside WebGLinput.
user just to call function like "WebGLInputFullScreen" instead Unity WebGL Template Fullscreen code.

but i need time to test it. sorry about that :(

**Comment by kou-yeung** [comment]
release a new version to support fullscreen.
and update the wiki for this.
https://github.com/kou-yeung/WebGLInput/wiki/Support-FullScreen
you can try it!

thanks~
