### ISSUE TITLE
Edge Browser: "appendChild" undefined

### ISSUE THREAD

**Issue by DeXtmL** [kou-yeung/WebGLInput#30]
To reproduce:
1. open a built WebGL project. (right click index.html and choose open with Edge)
2. click on an InputField with WebGLInput script attached.
3. Edge browser pops a warning says "appendChild" undefined or null, then stops working

In summary:
It works in editor but not in built release.

Lastest version of WebGLInput.
Unity 2019.1.3
Windows 10 x64

**Comment by kou-yeung** [comment]
i will check it.
thanks for report

**Comment by bantime** [comment]
you need to change your output html

var gameInstance = UnityLoader.instantiate("XXXXXXX", "Build/Web.json", {onProgress: UnityProgress});

XXXXXXX need 'unityContainer'

than change somewhere <div id="XXXXXX"></div> to <div id="unityContainer"></div>

**Comment by kou-yeung** [comment]
in Unity default template.
the canvas id is "unityContainer"

if you modified the canvas id.
you can use
`WebGLInput.CanvasId = xxxx`
to change the canvas id to append the input element.
