### ISSUE TITLE
Characters going invisible after certain point when using TextMeshPro Input

### ISSUE THREAD

**Issue by badagui** [kou-yeung/WebGLInput#34]
unity 2019.3.0f1

-Create a new project
-Set to WebGL build
-Import TextMeshPro and WebGLSupport
-Create an InputField(TMP)
-Add WebGLInput component
-Build and Run

After typing 40-50 characters they all become invisible. You can still select them, and they reappear if you go to beggining of line, and go inivisble again if you go to end.

edit: it won't bug in the editor, just when built
edit2: also it won't bug with the default InputField

**Comment by kou-yeung** [comment]
reproduced,i will try to fix it.
thanks for report.

**Comment by kou-yeung** [comment]
release a new package
https://github.com/kou-yeung/WebGLInput/releases/tag/0.7

but for this issue.
have Flashing to update the text mesh when using TMP.
i will fix it if i find a better way.

**Comment by mrobaczyk** [comment]
Hi @kou-yeung 
I have flashing too when updating text in TMP_Inputfield. Do you know any way to fix it?
