### ISSUE TITLE
Flashing when updating text in TMP_Inputfield.

### ISSUE THREAD

**Issue by kou-yeung** [kou-yeung/WebGLInput#35]
in #34.
when input a long text. the text going invisible.

workaround:
disable text one frame. and enable it at next frame.
but have flashing.
try to fix it

**Comment by kkarunakaran** [comment]
You mean in an update function?

**Comment by kou-yeung** [comment]
no.
When input a long text (around double size of text area)
Unity was culling the text(invisible).

so, in the input.Rebuild() function for TMP.
have a workaround to make it visible.
but this workaround will flashing one frame.

[https://github.com/kou-yeung/WebGLInput/blob/master/Assets/WebGLSupport/WebGLInput/Wrapper/WrappedTMPInputField.cs#L136](url)

i will try to fix it.

**Comment by kou-yeung** [comment]
Flashing alleviation. but not fixed yet
flashing long text only.
