### ISSUE TITLE
mobile keyboard continues on disable input field

### ISSUE THREAD

**Issue by fabsk7** [kou-yeung/WebGLInput#36]
when enable the input field run ok, but when disable the mobile keyboard do not disapear, each touch on screen appear the mobile keyboard. please help

**Comment by kou-yeung** [comment]
Supporting mobile keyboards is very difficult...

like iOS Safari
https://stackoverflow.com/questions/23722816/autofocus-text-field-on-mobile-but-no-keyboard

**Comment by fabsk7** [comment]
how do I get the keyboard out of the screen? when I disable the inputfield and touch the screen the keyboard reappears.

**Comment by AQE13H** [comment]
hi @kou-yeung, I also have a similar problem like this on mobile, still no fix yet? or is there a function to manually close the keyboard?

**Comment by kou-yeung** [comment]
@AQE13H 
i will try to support mobile device.
But the priority is low.
Because Unity WebGL is not support mobile browser..

FYR : https://docs.unity3d.com/2019.4/Documentation/Manual/webgl-browsercompatibility.html
`Note that Unity WebGL content is not currently supported on mobile devices. `

**Comment by kou-yeung** [comment]
i have release a new version to support mobile.
thanks~

**Comment by AQE13H** [comment]
thank you so much!

BEST REGARDS,

￼   S Y E D  F A Q I H

      J R  X R  D E V E L O P E R


￼  M I N I S T R Y  X R

     D - 1 - 3 A, B L O C K D 2,  R I T Z E  P E R D A N A  1  B U S I N E
S S  P A R K, B A N D A R  D A M A N S A R A  P E R D A N A

￼  + 6 0 1 9. 6 9 9 3 1 2 7       ￼  + 6 0 3  7 7 3 2  4 3 3 2.      ￼  S Y
E D. F A Q I H@ T H E M I N I S T R Y . A S I A


￼  M I N I S T R Y . X R

￼  F A C E B O O K . C O M / M I N I S T R Y X R

￼  Y O U T U B E . C O M / T H E  M I N I S T R Y A S I A

￼  I N S T A G R A M . C O M / M I N I S T R Y _ X R


￼

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2
