### ISSUE TITLE
initial text of text input not seen

### ISSUE THREAD

**Issue by nicanorrr** [kou-yeung/WebGLInput#37]
For my game, on start the game loads the old input string by the player using playerprefs.
When running in WebGL, initially the loaded string is not visible on the inputfield. When I click the inputfield, the loaded string appears but on the bottom of the window. However, when I toggle between different Loaded data, the input appears normally.

When opened:
![image](https://user-images.githubusercontent.com/65482727/82137923-c64c9480-984e-11ea-9470-88be40f74844.png)

When input field is clicked:
![image](https://user-images.githubusercontent.com/65482727/82137943-f85df680-984e-11ea-8c5b-4c85f2e4664d.png)

What different loaded data is toggled and what it should look like on startup:
![image](https://user-images.githubusercontent.com/65482727/82137940-ebd99e00-984e-11ea-822b-b2989ad9854a.png)

**Comment by kou-yeung** [comment]
can send me a sample reproduction project?
thanks you~

**Comment by nicanorrr** [comment]
My program with the bug can be seen here: https://nicanorrr.itch.io/random-draw-tool
Is this what you meant by the sample reproduction project? The bug happens when there is saved preset data and I refresh the page. (To make sure preset data is saved, toggle between the presets. I use OnApplicationQuit and toggling between presets to save the data but unfortunately I've just found out OnApplicationQuit doesn't work in WebGL).

So I tried to recreate the bug in a simpler scene to see if the problem would come up again and it didn't. You can view the simpler scene here: https://nicanorrr.itch.io/rdt-bug?secret=mPMfpNifCWnz8s8kwANvzcSvqO4

In this scene, I just put your WebGLInput component and my data preset loading code as well as a scrollbar. So it seems the bug has something to do with how some other objects in my main program are interacting with your code because the bug only appears in my main program in WebGL builds. However, I've tried turning on/off and disabling various parts of the program and I still haven't found out which part is causing the bug when interacting with WebGLInput.
I have suspicions that it maybe because of one of the following. Since you know your code better, maybe you can figure out what's causing the problem?

-  ForceLabelUpdate() which I use when loading new data into the input field. I tried commenting out these parts of the code though and the bug still reappears.
- I am using the Horizontal Scroll Snap from the UI Extensions package. I tried disabling this and bug still happens.
- In my main program, I manually set enableWordWrapping on the input field to false through script. I cannot set it in the inspector because the Multiline setting automatically enables enableWordWrapping. Also tried commenting this out and bug still happens.
- I'm using a component that prevents the input field from getting selected when I swipe because it is inside a horizontal scroll snap. Code was lifted from here: https://forum.unity.com/threads/inputfield-s-inside-a-scrollview.446976/. I tried disabling this and bug still happens.
- I don't know if my edits to your code to allow '\t' to be entered is causing it but when I tried reloading your original code, the bug still happens.

Let me know if you need more info :) Thank you :D

**Comment by kou-yeung** [comment]
thanks for your info.

how about your scroll rect content object default position?
maybe default position is bottom in scroll rect?

**Comment by nicanorrr** [comment]
When I run it in the editor, these are the scroll rect components of the horizontal scroll snap, the content object, and the panel which has the input field respectively.

![image](https://user-images.githubusercontent.com/65482727/82190352-7d1a4480-9923-11ea-843e-bfc9129d06d9.png)
![image](https://user-images.githubusercontent.com/65482727/82190375-84415280-9923-11ea-894d-4de746678f03.png)
![image](https://user-images.githubusercontent.com/65482727/82190420-94593200-9923-11ea-8902-d743ef12a632.png)

However, I just tried a build where i disabled the scroll rect and the horizontal scroll snap components and the bug still occurs.

**Comment by kou-yeung** [comment]
If you update to a newer version and need help, please contact us again.
thanks~
