### ISSUE TITLE
fullscreen edits affect viewport in itch.io

### ISSUE THREAD

**Issue by nicanorrr** [kou-yeung/WebGLInput#39]
after doing the edits to fix the fullscreen mode, when I uploaded the program to itch.io the game was vertically offcenter to the iframe. i used the auto-detect size setting.

auto-detect:
![image](https://user-images.githubusercontent.com/65482727/82139953-7970ba00-985e-11ea-86e6-b41b0ea77baf.png)

i am not using the manual setting and made it extra big. it is still off center. The margin on the top part is much bigger
![image](https://user-images.githubusercontent.com/65482727/82142717-ee4cef80-9870-11ea-8174-1fb042c785e7.png)

**Comment by kou-yeung** [comment]
Although editing the fullscreen is not highly recommended, Unity2020 will change the WebGL Template and you will no longer be able to use the previously defined methods.

I'm wondering if there's a better way

**Comment by nicanorrr** [comment]
I don't think it's a priority issue because I can just manually set the iframe size in itch.io. It won't look the best but maybe it's better to just wait for Unity2020 changes :) I can't suggest a better way because I'm not well-versed in html and css

**Comment by kou-yeung** [comment]
i have release a new version to support fullscreen.
no need edit the element style, just call a inject function only.

FYR:
https://github.com/kou-yeung/WebGLInput/wiki/Support-FullScreen

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.
