### ISSUE TITLE
problem as content of ScrollView

### ISSUE THREAD

**Issue by paptigshiyf** [kou-yeung/WebGLInput#41]
When I set InputField with a  WebGL input as a child of Content of UGUI ScrollView, it seems that the input field can not get my mouse position. It always selects all of the text when I click in the input filed, and i can't set the caret in the correct position. Is there any solution?
Thanks for your package, it helps a lot!

**Comment by paptigshiyf** [comment]
I'm a rookie, and I find it hard to solve it myself. Is there any solution?

**Comment by paptigshiyf** [comment]
emmmm i misunderstood its function. it always select everything >.<

**Comment by kou-yeung** [comment]
in TMP.you can set onFocusSelectAll flags to control text all selected or not.

**Comment by paptigshiyf** [comment]
Thanks for your reply, but i still find some problems. It seems that,  it always selects all of the text and could not pick a segment of it when I click on it it and drag on the text, as  in your sample.  In the contrast, keyboard control to select a segment works properly by using shift + ⬅➡. 
I'm a rookie, and i can't understand what is happening. The Title of this issue it totally wrong about my problem(′д｀ )…彡…彡 Thanks again!

**Comment by kou-yeung** [comment]
this plugins not support select text by mouse drag.
because this plugins is overlay a very small "input element" on canvas element.

so. when you begin drag.
it will
1.Out focus from "input element"
2.Recv a touch event and select Unity InputField again.
3.Active WebGLInput plugins and create a new "input element". (auto select all text)

**Comment by kou-yeung** [comment]
i can make a option( like a checkbox ) for WebGLInput component to switch "input element" type
1. very small "input element", but can not drag to select.
2. overlay a same size of Unity InputField. this can drag to select. but just can use system font.

**Comment by paptigshiyf** [comment]
THANKS Daddy ! ORZ!  I'm just using the system font actually, and have no need to use pretty font as in the TMP. Actually i use it as a simple text editor in the normal Canvas, so it might be long texts containing dozens of rows in MultiLineNewLine. Is it fine? 土下座

**Comment by kou-yeung** [comment]
yes, you can edit a long text MultiLineNewLine.

**Comment by kou-yeung** [comment]
released a new version to support select text by drag.
it will show input element on canvas.
just check the "showHtmlElement" at WebGLInput component.

you can try it.^^

**Comment by paptigshiyf** [comment]
get it! It works! Already enough for current use！Great Helps !
