### ISSUE TITLE
multiline-newline inputfield

### ISSUE THREAD

**Issue by Racines** [kou-yeung/WebGLInput#43]
Hello,
In your [demo](http://kou-yeung.mygamesonline.org/WebGLInputSample/index.html)
If you press enter in the inputfield with content type: MultiLine New Line
It seems to jump multiple times.
Also is your demo using TMP?

**Comment by kou-yeung** [comment]
the sample just setted "Line Space" to 2.
i will test for TMP use MultiLine New Line and update the sample for Line Space setting.

**Comment by kou-yeung** [comment]
demo updated.
fix Line Space
add TMP Input field sample

**Comment by Racines** [comment]
Ok thank you for your reactivity.

It's seem I have bugs using your plugin in my project but it's not happen in your demo.
I think these bugs come from specific stuff I use for my project. But maybe do you have an idea on this:

1. It seems that normal character inputs are not catched by the html inputfield but is catched by inputfield in Unity. The IME seems to work properly if not in ASCII mode.
2. Also `UnityEngine.WebGLInput.captureAllKeyboardInput = true;` seems to cause side effect like described here: https://answers.unity.com/questions/1541833/bug-with-webglinputcaptureallkeyboardinput.html?childToView=1748956#answer-1748956

**Comment by kou-yeung** [comment]
can you send me a reproduction project for this issue?

**Comment by Racines** [comment]
So after some research I finally found what cause this behavior.
Since the use of IME cause to loose some feature of Text Mesh Pro like mouse selection. In my project I want to be able to copy/paste without the need of IME (for latin language).
So I use both your plugin and [WebGLCopyAndPaste](https://github.com/greggman/unity-webgl-copy-and-paste)

I made a [simple project](https://github.com/kou-yeung/WebGLInput/files/4890810/WebGLInputConflictWebGLCopyAndPaste.zip) based on your source code where I added the other plugin.
The problem seems to be caused by WebGLCopyAndPaste.jslib at line 56.
Probably in conflict with your code when you call `UnityEngine.WebGLInput.captureAllKeyboardInput = true;`

Maybe are you able to advice me on this?

**Comment by kou-yeung** [comment]
for mouse selection. WebGLInput have a option to support it.
you can check on the "Show Html Element" flag to show a  HTML <input> element overlap on the input field.
(this can use all feature of HTML <input> element, but it will use system font at editing)

i will test the sample and try to fix it.
thank you~

**Comment by Racines** [comment]
Yes I see for the "Show Html Element" it work well but it break the immersion of the UI.

Thanks for your help.
