### ISSUE TITLE
null error

### ISSUE THREAD

**Issue by Anpu23** [kou-yeung/WebGLInput#46]
I am getting an odd null error when I put the build on the actual website.  Works fine in testing but when I upload it I get this error:
in Chrome its "uncaught TypeError: cannot read property "offsetWidth" of null" and in FireFox "TypeError container is null" It's only on the input fields that have the script WebGL Input attached.  Build is Unity 2019.4.0f1 website is a wordpress site.

**Comment by kou-yeung** [comment]
are you use custom index.html?
Because the default canvas id is "unityContainer" at Unity2019.1 or newer.
(maybe WordPress is use other name for canvas id?

**Comment by kou-yeung** [comment]
It seems that the sample page link is not attached.

but, i release a workaround for this issue.( container not found )
https://github.com/kou-yeung/WebGLInput/releases/tag/0.93

thanks~

**Comment by Anpu23** [comment]
Thank you so much.

**Comment by Anpu23** [comment]
So my understanding is the solution is this
 WebGLInput.CanvasId = " parentNode";
in static WebGLInput() correct? because that didn't seem to work
The game URL is https://adulttech.tech/game-room and is NOT SAFE FOR WORK!

**Comment by kou-yeung** [comment]
i found a same issue like this.

https://stackoverflow.com/questions/44590736/document-getelementbyid-gives-null-even-though-element-is-present

i not have idea to fix it now...
maybe you can try to use a iframe for your webgl game.

**Comment by Anpu23** [comment]
Thanks for trying.  If I figure out a solution I'll post it.
