### ISSUE TITLE
Mobile keyboard bugs

### ISSUE THREAD

**Issue by DerrickBarra** [kou-yeung/WebGLInput#47]
Hi @kou-yeung , thanks for your work on this! I found a couple of bugs with the experimental mobile WebGL input you should know about.

Bug 1
- Tap on an input field in Unity WebGL on mobile. The mobile input window appears as expected.
- Tap on the Unity WebGL Canvas, outside of a text input area.
Expectation: Mobile keyboard and javascript input prompt closes
Result: Nothing happens.

Bug 2
- Tap on an input field in Unity WebGL on mobile. The mobile input window appears as expected.
- On Android devices, tap the back button.
Expectation: Mobile keyboard and javascript input prompt closes
Result: Mobile keyboard closes, but the javascript input prompt remains

Bug 3
- Tap on an input field in Unity WebGL on mobile. The mobile input window appears as expected.
- Tap on a different input field on your Unity WebGL area.
Expectation: Mobile keyboard stays visible, and javascript input prompt changes to reflect the new input we've tapped
Result: Mobile input stays visible, and the javascript input prompt changes to the new input, however, the javascript input prompt is now located on top of the input box in Unity WebGL, instead of directly above the keyboard like normal.

Bug 4
- Tap on an input field in Unity WebGL on mobile. The mobile input window appears as expected.
- Destroy, disable, or lose focus on the input field in Unity WebGL
Expectation: Mobile keyboard and javascript input prompt hide
Result: Mobile keyboard and javascript input prompt remain visible

**Comment by kou-yeung** [comment]
thanks for your report.
i will check it~

**Comment by kou-yeung** [comment]
Memo:

Bug 1:
maybe this is default behavior at mobile.
in normal website. when the input element is focus and click other space.
input element is still active.

Bug 3:
not reproduction at iOS.
i will check for android device

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2
