### ISSUE TITLE
The mobile input still shows up after change a scene.

### ISSUE THREAD

**Issue by moomoo25** [kou-yeung/WebGLInput#48]
Hi, Kou Yeung, Thank you for this wonderful plugin. I have a problem that when I change the scene in my game the mobile input still shows up. Is there a proper way to close this when I change the scene?
Thank you.
![InputFieldShowsUp](https://user-images.githubusercontent.com/18592640/93113164-0af41980-f6e3-11ea-994a-d3f425b4f7c0.PNG)

**Comment by kou-yeung** [comment]
thanks for report!
can i have a simple project for this issues?

i will try blur the input when inputfield call OnDestroy()

**Comment by moomoo25** [comment]
Thanks for your reply, Here a ZIP for simple project.

[TextBoxProject.zip](https://github.com/kou-yeung/WebGLInput/files/5229528/TextBoxProject.zip)

**Comment by kou-yeung** [comment]
release a new version to Blur input when inputfield call OnDestory
https://github.com/kou-yeung/WebGLInput/releases/tag/0.95
thanks~

**Comment by moomoo25** [comment]
Much thanks Kou Yeung. I appreciate it.
