### ISSUE TITLE
it doesnt work with custom full screen buttons! on pointer down event

### ISSUE THREAD

**Issue by slagatoras** [kou-yeung/WebGLInput#51]
`  public override void OnPointerDown(PointerEventData eventData)
  {
    Screen.fullScreen = !Screen.fullScreen;
    base.OnPointerDown(eventData);
  }`

using this button to go full screen the keyboard wont show!

**Comment by kou-yeung** [comment]
i will add a function for this.
because Screen.fullScreen is work for canvas element.

**Comment by slagatoras** [comment]
oh on another project in unity 2020 it doesnt even work on fullScreen = true; on a onclick event any workarounds?

**Comment by ZhaoWuBao** [comment]
> i will add a function for this. because Screen.fullScreen is work for canvas element.

Do you support custom full-screen buttons now？

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.
