### ISSUE TITLE
When I input '你',it became whitespace

### ISSUE THREAD

**Issue by fashioncoolwan** [kou-yeung/WebGLInput#52]
![QQ截图20201030113509](https://user-images.githubusercontent.com/31815474/97657264-68ca9e00-1aa4-11eb-9816-15a0a529680d.png)

**Comment by fashioncoolwan** [comment]
I want to input ‘你好，世界！’,but can't see '你' in the textbox.

**Comment by kou-yeung** [comment]
the sample page is use japanese font.
this font not include "你".

so, you can change the font to support your target language and rebuild it!
thanks~
