### ISSUE TITLE
Cannot build project with WebGLInput TAB functionality

### ISSUE THREAD

**Issue by babazookz** [kou-yeung/WebGLInput#53]
When I try to build project in Unity 2019 with enabled TAB functionality this is the error I get

https://i.imgur.com/KMEW6MG.png

**Comment by babazookz** [comment]
Did you find the root cause?

**Comment by kou-yeung** [comment]
missing for this commit.

https://github.com/kou-yeung/WebGLInput/commit/2b16bc8fc56177f96e74fbebbe20773a5e4dccb9#diff-bad2f5864f474b4b4bda7c64e4e472a34ddbbe3bbee0a0a2f90f05956053a95fR66

try to test for support mobile.
but changed used function name...

reverse the function to "WebGLInputEnableTabText" this will work.
( "WebGLInputOnFocusOut" is not used function )

**Comment by kou-yeung** [comment]
fixed
https://github.com/kou-yeung/WebGLInput/releases/tag/0.96

**Comment by babazookz** [comment]
Hey, building a project is fixed but moving between INPUT FIELDS with TAB is not working.

Is there any video or demo to see how it should be working? I followed the instructions of yours for setting this up but nothing helped.

Did you check is that functionality still working?
