### ISSUE TITLE
Option to select/copy only parts of the string?

### ISSUE THREAD

**Issue by fib00nacci** [kou-yeung/WebGLInput#54]
Hi,
awesome solution you created there, many thanks!

However it would be nice to also have the option to select only a certain part of the text in the InputField instead of automatically selecting the whole String when clicking on it.

**Comment by ben842002** [comment]
I know this is an old post but I was wondering if there was any solution that was implemented by anyone? Thanks.

**Comment by kou-yeung** [comment]
![image](https://github.com/kou-yeung/WebGLInput/assets/7277282/01fe3669-8581-4be4-89b7-f3ee2350d5de)
it can enable html element to select parts of string
