### ISSUE TITLE
Reversed text on Chrome full screen

### ISSUE THREAD

**Issue by GabrielCerra** [kou-yeung/WebGLInput#56]
Hi!

First, thank you for this plugin, is a must for WebGl. But, I'm experimenting a very weird bug on Chrome with the app in full screen. Any input I use in full screen reverses the order of the text like "olleh".

I would try to debug it on a clean project but, if anyone has any hint to fix this issue I will really appreciate it.

Cheers!

**Comment by kou-yeung** [comment]
This plugins not work for default unity fullscreen.

you can follow ↓ to setup for fullscreen
FYR: https://github.com/kou-yeung/WebGLInput/wiki/Support-FullScreen
*but not support Unity 2020...

**Comment by GabrielCerra** [comment]
Thank you!

I will do some test and let you know if everything works fine :)

Cheers!

**Comment by GabrielCerra** [comment]
Hi Kou,

I did a few tests with your advice but, if I try to get in full screen mode, I get the error "makeFullscreen is not a function". Project is on Unity 2019, don't know if I am missing something.

Thank you!

**Comment by kalyanikolape** [comment]
Hi Kou and GabrielCerra,

I am facing same issue on full screen.  I tried to get into fullscreen with makeFullScreen but I faced same error as GabrielCerra faced.

Please help me.

Thank you!

**Comment by ohaddahan** [comment]
Yeah same issue here.

**Comment by 1samuel411** [comment]
Occurring here too

**Comment by akroshteotia** [comment]
Is this issue solved? We are using 2021 and i don't see any error but still it works backwards.

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.
