### ISSUE TITLE
Disable Auto Zoom in

### ISSUE THREAD

**Issue by MuhaiminMuhamad** [kou-yeung/WebGLInput#57]
just simple question , how to disable auto zoom in when click input field for mobile browser?

**Comment by kou-yeung** [comment]
https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone/6394497
`The browser will zoom if the font-size is less than 16px and the default font-size for form elements is 11px (at least in Chrome and Safari).
`

**Comment by MuhaiminMuhamad** [comment]
ah yes, its working thanks
i put this code on header
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
