### ISSUE TITLE
Question: how to trigger copy function through Unity script

### ISSUE THREAD

**Issue by marioslokas-v** [kou-yeung/WebGLInput#58]
Hi,

I am making a webgl build where the user should be able to copy a code to their system clipboard while pressing on a button, instead of using ctrl+c. With the WebGLInput script, the user can use the ctrl+c functionality only. Is there a way to trigger that through a script using your code?

**Comment by kou-yeung** [comment]
no.
・copy text to clipboard by script is not a feature for WebGLInput.
・you can use "Clipboard API".( maybe need Promise )
・FYR: https://www.w3schools.com/howto/howto_js_copy_clipboard.asp
