### ISSUE TITLE
Error Uncaught NotFoundError

### ISSUE THREAD

**Issue by BhaktiugpMrAR** [kou-yeung/WebGLInput#59]
I am getting an Uncaught NotFoundError that says:

"Failed to execute "removeChild" on "Node": The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler."

It occurs when I am changing the scene with keyboard input still opens. Please help, thank you very much

**Comment by BhaktiugpMrAR** [comment]
My current solution is adding try catch inside the WebGLInput.jslib on line 146 inside WebGLInputDelete function
`WebGLInputDelete:function(id){
        var input = instances[id];
		try {
        	input.parentNode.removeChild(input);
		}
		catch(err) {

		}
        instances[id] = null;
},`

And call DeactivateInputField() method before changing scene on all WebGLInput inside that scene.

But I still need the correct solution to prevent other problems in the future. Please help, thank you very much.

**Comment by kou-yeung** [comment]
is it for mobile build?

**Comment by BhaktiugpMrAR** [comment]
Yes, it is. I currentlhy working on unity webgl for mobile

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2

if reproduction at new release. reopen it.
thanks~
