### ISSUE TITLE
TextMesh Pro support

### ISSUE THREAD

**Issue by mhama** [kou-yeung/WebGLInput#6]
Hi, I tried to add WebGLInput component to a GameObject that has a TextMeshPro TMP_InputField  component, but failed because of an error below. It seems to be a effect of `[RequireComponent(typeof(InputField))]`

![image](https://user-images.githubusercontent.com/618417/57671617-7f322f00-764f-11e9-97e6-b1ffb5955663.png)

So I hope that WebGLInput can be used with TextMeshPro.

I also think about the implementation a bit, InputField and TMP_InputField shares almost the same methods but not same interface.
So creating a new interface and wrap these classes and apply the same interface may be the way to go.

```
interface IInputField {
  RectTransform textComponenRectTransform();
  ...
}

class WrappedTMPInputField : IInputField {
  private TMP_InputField target;
  public RectTransform textComponenRectTransform() {
    return target.textComponent.GetComponent<RectTransform>();
  }
  ...
}
```

Then it becomes able to write code against the interface.

**Comment by kou-yeung** [comment]
it’s good idea.
i will try to support TMP_InputField.

**Comment by kou-yeung** [comment]
release a new version to support TextMeshPro.
