### ISSUE TITLE
Mobile browser won't pan back out after entry

### ISSUE THREAD

**Issue by DaniBMGS** [kou-yeung/WebGLInput#60]
On mobile (Safari on Iphone X) the viewport zooms in on field entry, which is certainly a behavior I want. The second field allows entry as well, but upon the keyboard closing and clicking outside the fields, the viewport seems to be stuck, it will not zoom back out or allow thumb panning. If anyone else has had this problem and knows how to fix it, I would love some help!

**Comment by kou-yeung** [comment]
this not plugins issues.

FYR : https://stackoverflow.com/questions/6030319/how-to-trigger-iphone-zoom-out-after-auto-zoom-in-to-a-form

**Comment by kou-yeung** [comment]
If the input's font-size is a minimum of 16px the zoom in will not be triggered to begin with.
