### ISSUE TITLE
Issue on iOS (reversed text)

### ISSUE THREAD

**Issue by QuentSF** [kou-yeung/WebGLInput#64]
Hello,

Thanks for the plugin it works great on android.

But on iOS I have reverse text with an error "Cursor locking is not supported on the browser". I don't know if it's related.

Have you got any idea how to solve this problem? I Will continue to work on your source code with the hope to find a solution.

I activate your plugin on this sample only for Android and iOS. It's not activate on desktop.

https://share.seriousfactory.com/Interne/2020/Module/

Quentin

**Comment by kou-yeung** [comment]
are you use "Pointer_Lock_API"?
FYR : https://developer.mozilla.org/ja/docs/Web/API/Pointer_Lock_API#browser_compatibility
this api is no support "Safari on iOS".
