### ISSUE TITLE
Unity 2021.2 B11 throw pointer_stringfy is not defined error

### ISSUE THREAD

**Issue by kenofori** [kou-yeung/WebGLInput#65]
Hi there,

Your plugin is amazing and it worked well with previous versions of Unity, However Unity 2021.2 B11 is throwing this error.

Please advise

![image](https://user-images.githubusercontent.com/30837872/132944857-e5e3f8b6-8b80-4bba-ae3c-8323986e95af.png)

**Comment by kou-yeung** [comment]
Release a new package support Unity2021.2.0b12
https://github.com/kou-yeung/WebGLInput/releases/tag/1.0
