### ISSUE TITLE
Canvas stay zoomed after edit text

### ISSUE THREAD

**Issue by lMasc** [kou-yeung/WebGLInput#66]
Hi,
I have the following issue in Mobile , Android Chrome browser (not tested in other browsers) :

- I can show the mobile keyboard after pressing an inputfield    ✓ 
- After hitting "Enter" the edition of the inputfield ends    ✓
- The view keeps zoomed and it wont back to the Original size    X

 Here are some images of the problem im facing;

Before edit inputfield

![5QMQvQTfvp](https://user-images.githubusercontent.com/32910255/134070305-32b886ce-2fd8-42b1-9ffe-fab04ea43606.png)

After edit inputfield

![y6XknwJ8qn](https://user-images.githubusercontent.com/32910255/134070462-de2d06c5-7d21-41a4-84cb-d0f935e64b46.png)

**Comment by kou-yeung** [comment]
FYR : https://uxcellence.com/2014/fix-ios-input-zoom
you can change the font size to fix it.

**Comment by kou-yeung** [comment]
if your application not need the autozoom.you can try to disable it.
https://stackoverflow.com/questions/4472891/how-can-i-disable-zoom-on-a-mobile-web-page

**Comment by lMasc** [comment]
Thank you very much pointing me in the right direction !
I implement a solution from the link you gave me and it works.
Thanks again !
