### ISSUE TITLE
Safest way to hide the auto-generated input field manually

### ISSUE THREAD

**Issue by lMasc** [kou-yeung/WebGLInput#67]
Hi , its me again 😅 

**I would like to know if there is a way to hide the autogenerated html input field manually ?**
(to use it when the user click outside the input or when the user click a button or interact with other elements ) .

Now the inputfield closes fine when the user hit enter on the virtual keyboard. But if the user press another Unity UI element then the html inputfield stays on screen, and the only way to make it desapair is pressing enter in the virtual keyboard.

**Comment by kou-yeung** [comment]
I'm trying are other approach to support mobile device.
e.g.
add a inputfield upper at keyboard instead overlay on inputfield.

and i think the same thing for this.
when user tap the screen outside of inputfield . this can close the keyboard.
i hope next release can work...

**Comment by kou-yeung** [comment]
sample movie for the new approach.
https://user-images.githubusercontent.com/7277282/134623706-ebf2e6ba-09cb-44fd-be40-37ce3b9a247b.mp4

this look like [WebGLNativeInputField](https://github.com/unity3d-jp/WebGLNativeInputField)
but usage rules is same of WebGLInput. not need other settings.

**Comment by lMasc** [comment]
Wow that looks neat . 
Looking forward for the new release then !

**Comment by kou-yeung** [comment]
pre-release a new package use new approach.
https://github.com/kou-yeung/WebGLInput/releases

If any questions or suggestion, feel free to contact me.
thanks~

**Comment by lMasc** [comment]
Hey, thank you !
The new release works flawlessly ✨
