### ISSUE TITLE
Can't run project when script imported

### ISSUE THREAD

**Issue by bitfreaks** [kou-yeung/WebGLInput#69]
Hi,

As soon as I import this script - I cannot run my project. Below is the log

Popup error:
```
abort({}) at jsStackTrace@https://********/landing/beta/Build/BFbetaTestingRelease.framework.js:739:12
stackTrace@https://********/landing/beta/Build/BFbetaTestingRelease.framework.js:753:11
abort@https://********/landing/beta/Build/BFbetaTestingRelease.framework.js:19:44
instantiateArrayBuffer/<@https://********/landing/beta/Build/BFbetaTestingRelease.framework.js:1189:10
```

Console error:
```
failed to asynchronously prepare wasm: LinkError: import object field 'nullFunc_fiiiii' is not a Function
LinkError: import object field 'nullFunc_fiiiii' is not a Function
```

**Comment by kou-yeung** [comment]
can you tell me which version of unity?

**Comment by bitfreaks** [comment]
Hey Kou, thanks for replying.

Unity 2020.3.19f1

**Comment by kou-yeung** [comment]
i tried Unity 2020.3.19f1 to create a empty project.
add a InputField with WebGLInput (https://github.com/kou-yeung/WebGLInput/releases/tag/1.0)
and [ Build and Run ] it.
but i cann't reproduction this issues.

maybe your webside have permission restrictions for some function?

**Comment by Artemis-chan** [comment]
try using the experimental build [1.1](https://github.com/kou-yeung/WebGLInput/releases/tag/1.1). I was having same issue. Fixed by using that version.
