### ISSUE TITLE
WebGL: Content type validation not working in TMP_InputField

### ISSUE THREAD

**Issue by mrobaczyk** [kou-yeung/WebGLInput#71]
Hi. I'm using your asset on my inputfields and I'm also using TextMeshPro version 2.1.6. I'm using Unity 2019.4 LTS. In my inputfields I'm using content type = Decimal number and a limit of 6 characters. In TextMeshPro 2.1.6 the decimal separator for the input validation is taken from CurrentCulture. On all my inputfields I'm using your WebGLInput script.
But in the webGL build the validation is not working. I can type multiple decimal separators (both!) - the input can be for example `...,,,` which is nonsense. I can also type any letter or symbol... while I should be able to write only digits, minus sign and decimal separator. In unity editor everything works fine.

Have you also encountered this problem?
Cheers
Mike

![image](https://user-images.githubusercontent.com/35763893/143422445-e71aa481-13f4-4635-a5c8-4c05f9497017.png)

**Comment by kou-yeung** [comment]
released a new version for fix this issues.
https://github.com/kou-yeung/WebGLInput/releases/tag/1.2.1
