### ISSUE TITLE
ReferenceError: Runtime is not defined _WebGLWindowOnFocus

### ISSUE THREAD

**Issue by maskedmouse** [kou-yeung/WebGLInput#72]
Using the newest [release version](https://github.com/kou-yeung/WebGLInput/releases/tag/1.0) 
Using Unity 2021.2.3
Development Build

I seem to get errors clicking / dragging inside the webgl window.

ReferenceError: Runtime is not defined _WebGLWindowOnFocus
ReferenceError: Runtime is not defined _WebGLWindowOnBlur
ReferenceError: Runtime is not defined _WebGLWindowOnResize

Just tested this in a clean project. Clicking inside worked but once I clicked outside it threw the errors.

Edit:
After fixing it manually by checking `if(typeof(Runtime) !== 'undefined')` It throws another error.
Assertion failed: allocate no longer takes a type argument

My guess is, emscripten has been updated. I looked up the documentation of `allocate` and indeed it only has 2 parameters.
so I went and removed the "i8".

`var value = allocate(intArrayFromString(input.value), ALLOC_NORMAL);`

After doing the `undefined` check and the `allocate` fix it seems to work now.

**Comment by AdionNn** [comment]
function _WebGLWindowOnBlur(cb) {
        window.addEventListener("blur", function() {
            Runtime.dynCall("v", cb, [])
        })
    }
    function _WebGLWindowOnFocus(cb) {
        window.addEventListener("focus", function() {
            Runtime.dynCall("v", cb, [])
        })
    }
    
    To be more exact, Problem is that in unity 2021, RunTime.dynCall doesn't exist anymore and it was changed to Module['dynCall_*']. Same error goes with Unity webSockets and etc. I am trying to rename it to Module by my self to check if that fixes error, but to be honest Idk if Unity team will fix this error back to how it used to be, or developers will need to adapt to it. Also version 1.0 and 1.1 does not fix this plugin error.  It would be nice if more information would be available.
    (more about it here https://stackoverflow.com/questions/70411564/unity-webgl-throws-error-referenceerror-runtime-is-not-defined)
