### ISSUE TITLE
Can't copy from inputfield on Android  

### ISSUE THREAD

**Issue by danielkotzer** [kou-yeung/WebGLInput#73]
Hi,
On PC Desktop everything seems to work fine, but when I open the WebGL I made with Unity on my Android device browser, I can't copy, I press on the text for a long time, but no popup is showing letting me copy or paste like when you want to copy and paste on other apps, you have to press for some time and then the word is selected and you are asked if you want to copy of paste..., here it is not working, Am I doing something wrong?

I installed version 1, of WebGLInput, but I saw on a forum that it is supporting Mobile devices:
[https://forum.unity.com/threads/webgl-copy-paste-for-input-field-not-working.494765/](https://forum.unity.com/threads/webgl-copy-paste-for-input-field-not-working.494765/)

I didn't want to use an experimental version 1.1, but I can install it if I have to.
Thanks
Daniel

**Comment by kou-yeung** [comment]
you can try to switch on "showHtmlElement" at WebGLInput component.
it will make the input element visible.

the experimental version 1.1 is make a input element on the keyboard like the native app.

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2
