### ISSUE TITLE
Mobile inputfield doesn't work

### ISSUE THREAD

**Issue by boasbakker** [kou-yeung/WebGLInput#74]
![image](https://user-images.githubusercontent.com/59883944/152423898-1d8a513d-71c1-4d9e-ab6e-e7bc58baf45f.png)
I get this error when selecting the inputfield.
I have an android phone and opened my own site with google chrome

**Comment by kou-yeung** [comment]
Which version of Unity are you using?

**Comment by boasbakker** [comment]
Latest 2019 LTS

**Comment by boasbakker** [comment]
Should I send my project or the javascript log or?

**Comment by boasbakker** [comment]
Maybe it is because I use an textmeshpro inputfield?
Your demo does work for me

**Comment by boasbakker** [comment]
Can you please fix this?

**Comment by kou-yeung** [comment]
i tried use Unity 2019.4.35f1 is work.
and it work with tmp inputfield.

can i have the reproduction project for this issue?

**Comment by boasbakker** [comment]
Yeah the test project (updated to my version) also worked. I am going to try to copy the gameobject directly from the project to the scene

**Comment by boasbakker** [comment]
Exception: Can not Setup WebGLInput!!
WebGLSupport.WebGLInput.Setup () (at Assets/WebGLSupport/WebGLInput/WebGLInput.cs:137)
WebGLSupport.WebGLInput.Awake () (at Assets/WebGLSupport/WebGLInput/WebGLInput.cs:142)

In the test project, this error appears with the TMP inputfield

**Comment by boasbakker** [comment]
Okay I copied the files from the preview project and it does work now, no idea what was wrong.
