### ISSUE TITLE
The caret is always at the first character in fullscreen mode, so you need to type backwards.

### ISSUE THREAD

**Issue by boasbakker** [kou-yeung/WebGLInput#77]
As the title sais

**Comment by XtroTheArctic** [comment]
This is a big problem for us.

Can you help please?

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.

**Comment by kou-yeung** [comment]
if reproduction at new release. reopen it.
thanks~
