### ISSUE TITLE
UI builder

### ISSUE THREAD

**Issue by AdionNn** [kou-yeung/WebGLInput#78]
Is there any plans for UI builder support? New UI system on unity 2021 and above.

**Comment by kou-yeung** [comment]
No.sorry.

**Comment by manofspirit** [comment]
+ 1 for UI Toolkit Support

**Comment by camenduru** [comment]
+1

**Comment by kou-yeung** [comment]
release a new version to support UIToolkit (Experimental)
[1.3.4](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.4)
