### ISSUE TITLE
Assertion failed: allocate no longer takes a type argument

### ISSUE THREAD

**Issue by tomkail** [kou-yeung/WebGLInput#79]
WebGLInputOnValueChange and WebGLInputOnEditEnd call `allocate(intArrayFromString(input.value), 'i8', ALLOC_NORMAL);`, which causes the error `Assertion failed: allocate no longer takes a type argument` on WebGL on Unity 2021.2.7.
I don't really understand this but I've fixed it by changing the line to `var value = allocate(intArrayFromString(input.value), ALLOC_NORMAL);`

**Comment by kou-yeung** [comment]
release a new package for support this issues.
thank you for report!
https://github.com/kou-yeung/WebGLInput/releases/tag/1.2
