### ISSUE TITLE
HTMLInputElement is not collecting by GC

### ISSUE THREAD

**Issue by parkoma** [kou-yeung/WebGLInput#81]
hi, i have some issue to use this plugin for webgl.

when i focus on input field, this plugin create HTMLInputElement.

That is so cool, but that is not collecting by GC.

i show my screenshots

![image](https://user-images.githubusercontent.com/26456131/158552500-1f3052e5-e5cb-4bed-94f1-4fa5e7191134.png)

when i click input field, 329MB in chrome memory snapshot

and refresh the browser

![image](https://user-images.githubusercontent.com/26456131/158552824-0e91de12-62c1-4fe2-be0c-62fe534dc2fb.png)

memory is doubling...

how can i fix that issue? plz i want to know about that and i upload my snapshots for HTMLInputElement

1. Detached HTMLInputElement
![image](https://user-images.githubusercontent.com/26456131/158553148-ce229957-a341-415c-900c-3a71e71868c1.png)
![image](https://user-images.githubusercontent.com/26456131/158552500-1f3052e5-e5cb-4bed-94f1-4fa5e7191134.png)
HTMLInputElement @28801 is not collecting by GC

**Comment by kou-yeung** [comment]
this plugins was remove the input element when InputField was un focus
https://github.com/kou-yeung/WebGLInput/blob/master/Assets/WebGLSupport/WebGLInput/WebGLInput.jslib#L168

which version of Unity you used and can  have a reproduction sample project?

**Comment by parkoma** [comment]
1. Unity Version : 2020.2.1f1

2. https://object-storage.tyo1.conoha.io/v1/nc_df3bdbc45bc04950b558834f5728517a/unityroom_production/game/14900/webgl/play.html <- that is your sample.

when you go to that website, if you follow the steps memory leak has been appeared.
Step1. Focus on the Input Field.
Step2. Input any string (e.g Hello, world etc...)
Step3. Blur the Input Field.
Step4. Refresh website.
Step5. Memory Doublling.
Step6. Focus on the refreshed website's Input Field, memory get lower.

**Comment by kou-yeung** [comment]
i tried same step with google.com.
i think this is a default behavior?

https://user-images.githubusercontent.com/7277282/158767031-2f45f7c5-bb22-44b6-8253-8f819f714602.mp4

and same questions for borwser refresh ?
https://stackoverflow.com/questions/11286451/browser-refresh-does-not-do-garbage-collection

**Comment by parkoma** [comment]
i think that is problem of browsers. thanks for check my issue!
