### ISSUE TITLE
Fullscreen is work not correct

### ISSUE THREAD

**Issue by khanhcodestringers** [kou-yeung/WebGLInput#82]
at fullscreen mode, i cant use button arrow ( left, right .. ) for move cursor to another words.

**Comment by MahraneAbid** [comment]
same copy past dosent work in full mode

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.

**Comment by kou-yeung** [comment]
if reproduction at new release. reopen it.
thanks~
