### ISSUE TITLE
TextMeshPro Input Field doesn't exclude letters with content type set on Decimal Number

### ISSUE THREAD

**Issue by Andrea332** [kou-yeung/WebGLInput#83]
I have noticed that the component "TextMeshPro Input Field" with the "content type" setted only on Decimal Number doesn't exclude letters anymore when typing in the final builded game, but in editor everything works fine, obviously i have the "WebGLInput" Script attached to it.

I'm building on Unity 2021.2.16f1 | TextMeshPro package 3.0.6 | Input System 1.3.0 | kou-yeung Web GL Input 1.2

<img width="380" alt="WebGlInput" src="https://user-images.githubusercontent.com/74671832/160155183-ecd13943-19b5-4ecc-9699-f6ac5f5d75f2.png">

**Comment by kou-yeung** [comment]
same issues of #71 ?

**Comment by kou-yeung** [comment]
released a new version for fix this issues.
https://github.com/kou-yeung/WebGLInput/releases/tag/1.2.1

**Comment by kou-yeung** [comment]
WebGLInput is use TMP_InputField.text = "xxx" to update the text from HTML input element.
but, TMP_InputField.text = "xxx" is set the text directly.
so, create a inactive InputField to filiter the content type.

https://github.com/kou-yeung/WebGLInput/blob/master/Assets/WebGLSupport/WebGLInput/Wrapper/WrappedTMPInputField.cs#L28
