### ISSUE TITLE
when i build this project. my mobile 📱 browser  doesn't pop up keyboard 

### ISSUE THREAD

**Issue by Azizkhan007** [kou-yeung/WebGLInput#84]
when i clicked on my input field via mobile 📱 browser. it doesn't pop up my keyboard  
kindly help to fix that issue.
i simply download repository from ur profile  [(https://github.com/kou-yeung )] 
and import to my project and then build it

**Comment by kou-yeung** [comment]
have you add "WebGLInput" Component to InputField GameObject?

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2
