### ISSUE TITLE
Android input field visibility issue

### ISSUE THREAD

**Issue by kokyang** [kou-yeung/WebGLInput#93]
Good morning, 
I notice some css/positioning issue.

When using android, focus on input input field, keyboard will appeared, 
but the input field (places that we are going to enter text) is blocked by keyboard.

iOS seems normal, input fields will appear on top position of keyboard.

is any settings able to adjust the input input fields position?

**Comment by kou-yeung** [comment]
mobile is support by unity
・InputField : from Unity2022.1
・TMP_InputField : from Unity2023.2
