### ISSUE TITLE
how show input number only

### ISSUE THREAD

**Issue by emilisa707** [kou-yeung/WebGLInput#95]
I set up my input field only for numbers. but when I build the project and deploy it to the web I can type all characters not only numbers there. how to fix it?

**Comment by kou-yeung** [comment]
the sample https://unityroom.com/games/webglinput is work for ContentType setting.

which unity version you used?
can i have a reproduction project for this issues?

**Comment by emilisa707** [comment]
is it compatible also for Text Mesh Pro??

**Comment by kou-yeung** [comment]
i think yes.
this plugins is input a text by html input element and set the text to InputField (or TMP)

but i remember the ContentType setting of tmp input filed is not work for text setter.
you can try to set the text to tmp input field directly.

**Comment by kou-yeung** [comment]
`the ContentType setting of tmp input filed is not work for text setter.`
maybe this is a tmp inputfield bug. you can report this to unity...

**Comment by kou-yeung** [comment]
tried in unity2022.3.4f1.
TMP input is correct for ContentType.
