### ISSUE TITLE
Keyboard don't show on mobile browsers in fullscreen mode

### ISSUE THREAD

**Issue by huyhungkun** [kou-yeung/WebGLInput#96]
As title, I can't type anything in fullscreen mode. I tested on chrome in Samsung device. I use Unity 2021.3.6f1. How to fix it?

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.

if reproduction at new release. reopen it.
thanks~
