### ISSUE TITLE
Backwards typing in fullscreen mode

### ISSUE THREAD

**Issue by EmanueleBagnarola** [kou-yeung/WebGLInput#99]
Hi! I am experiencing this odd bug that will make the typing inside of the input fields go backwards when the game is in fullscreen mode. For example if I need to type "hello", the input field will only make me type "olleh". Any idea of what could cause this issue?

**Comment by markv12** [comment]
I am also having this issue

**Comment by gebalassa** [comment]
Happens both in Edge and in Chrome.

Strangely, **F11** works fine on both, but activating "fullscreen" through a Javascript button creates the issue.

**Comment by DiscreteTom** [comment]
Here is a demo game which can produce this issue: https://discretetom.github.io/CannonVsMosquito/

Looks like the cursor is locked at the beginning of the input field and can't be moved.

**Comment by kou-yeung** [comment]
release a new version for fullscreen.
[release](https://github.com/kou-yeung/WebGLInput/releases/tag/1.3.3)

you can call WebGLSupport.WebGLWindow.SwitchFullscreen() from your app to switch fullscreen.

**Comment by kou-yeung** [comment]
if reproduction at new release. reopen it.
thanks~
